version: '3'

services:
    web:
        build: .
        ports:
            - "10287:5000"
        depends_on:
            - brevetdb 
        environment:
            MONGODB_HOSTNAME: brevetdb
    brevetdb:
        image: mongo:latest
